require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Metrics/MethodLength:
  Max: 40

RSpec/NestedGroups:
  Enabled: false

Metrics/ClassLength:
  Max: 200
